name: CI

on:
  push:
    branches:
      - iceraven
  workflow_dispatch:

jobs:
  build-specific:
    name: Build forkRelease arm64-v8a
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      - name: Create version name
        run: echo "VERSION_NAME=$(git describe --tags HEAD)" >> $GITHUB_ENV

      - name: Install Android SDK
        run: |
          echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties
          ./automation/iceraven/install-sdk.sh

      - name: Patch strings
        run: |
          ./automation/iceraven/patch_android_components.sh
          sed -i 's/Firefox/Iceraven/g' app/src/main/res/values*/*strings.xml
          sed -i '/about_content/s/Mozilla/@forkmaintainers/' app/src/main/res/values*/*strings.xml

      - name: Build ONLY forkRelease
        run: |
          ./gradlew app:assembleForkRelease \
            -PversionName=${{ env.VERSION_NAME }} \
            --no-daemon

      - name: Sign arm64 APK
        run: |
          BUILD_TOOLS=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          mkdir -p signed
          
          $ANDROID_HOME/build-tools/$BUILD_TOOLS/apksigner sign \
            --ks <(echo "${{ secrets.DEBUG_SIGNING_KEY }}" | base64 -d) \
            --ks-pass pass:${{ secrets.DEBUG_KEY_STORE_PASSWORD }} \
            --ks-key-alias ${{ secrets.DEBUG_ALIAS }} \
            --key-pass pass:${{ secrets.DEBUG_KEY_PASSWORD }} \
            --out signed/app-arm64-v8a-forkRelease.apk \
            app/build/outputs/apk/forkRelease/app-arm64-v8a-forkRelease.apk

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: signed/app-arm64-v8a-forkRelease.apk
          name: ${{ env.VERSION_NAME }}-arm64-forkRelease
